### ISSUE TITLE
Issue running installation script

### ISSUE THREAD

**Issue by vischulisem** [pardojer23/RNAseqV2#1]
I cloned the repository, went into the RNAseqV2 directory and typed: python setup.py install

I got this error: error: [Errno 13] Permission denied: '/Users/elysevischulis/opt/anaconda3/lib/python3.8/site-packages/easy-install.pth'

<img width="930" alt="Screen Shot 2020-10-26 at 2 06 33 PM" src="https://user-images.githubusercontent.com/52712211/97210851-8e9a2f00-1794-11eb-9d96-66111fd8575c.png">

I am not sure if it is because I have python 3.8 and RNAseqV2 requires python 3.6? Not sure what to do to resolve this.

**Comment by pardojer23** [comment]
Could you give me some more information about the environment you tried to install in?

**Comment by vischulisem** [comment]
I'm installing on terminal on a mac. I already have a python environment
set up. I'm in Foundations with Bob and he said he had the same issue
installing too.

**Comment by pardojer23** [comment]
Try running `python setup.py install --user` (to install locally) or `sudo python setup.py install` to install globally. Let me know if that helps!

**Comment by vischulisem** [comment]
This worked. Thank you!
