### ISSUE TITLE
snakemake 3.13.3 doesn't support directory

### ISSUE THREAD

**Issue by reidoko** [pardojer23/RNAseqV2#4]
In `RNAseqV2/envs/RNAseqV2.yml`, it specifies `snakemake=3.13.3`, but this version doesn't support `directory()`, which is used in line 122 of `RNAseq.smk`. 5.27.4 does support this, but I don't know which version is the earliest that supports it.

**Comment by pardojer23** [comment]
It is my understanding that the `directory` flag was introduced as a requirement in 5.2.0 but that including it under a previous version has no negative impact. Do you have a case where this breaks the pipeline?

**Comment by pardojer23** [comment]
I updated the pipeline to require snakemake >=5.2.0
